name: My First GitHub Action

on:
  push:
    branches:
      - main
      - feature/add-course-file

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print Hello
        run: echo "Hello from GitHub Actions!"

      - name: Show current directory
        run: pwd

      - name: List files
        run: ls -la